onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/clk
add wave -noupdate /main/nasty_one_bit
add wave -noupdate /main/rst_n
add wave -noupdate -expand -subitemconfig {{/main/t_ep2tru[0]} -expand} /main/t_ep2tru
add wave -noupdate /main/t_req
add wave -noupdate /main/t_resp
add wave -noupdate /main/t_rtu
add wave -noupdate /main/t_tru2ep
add wave -noupdate /main/tru_ep2tru
add wave -noupdate /main/tru_req
add wave -noupdate /main/tru_resp
add wave -noupdate /main/tru_rtu
add wave -noupdate /main/tru_swc2tru
add wave -noupdate /main/tru_tru2ep
add wave -noupdate -divider xTRU
add wave -noupdate /main/DUT/X_TRU/clk_i
add wave -noupdate /main/DUT/X_TRU/ep_i
add wave -noupdate /main/DUT/X_TRU/ep_o
add wave -noupdate /main/DUT/X_TRU/g_mt_trans_max_fr_cnt
add wave -noupdate /main/DUT/X_TRU/g_num_ports
add wave -noupdate /main/DUT/X_TRU/g_pattern_mode_width
add wave -noupdate /main/DUT/X_TRU/g_pattern_width
add wave -noupdate /main/DUT/X_TRU/g_patternID_width
add wave -noupdate /main/DUT/X_TRU/g_pclass_number
add wave -noupdate /main/DUT/X_TRU/g_prio_width
add wave -noupdate /main/DUT/X_TRU/g_stableUP_treshold
add wave -noupdate /main/DUT/X_TRU/g_tru_addr_width
add wave -noupdate /main/DUT/X_TRU/g_tru_entry_num
add wave -noupdate /main/DUT/X_TRU/g_tru_subentry_num
add wave -noupdate -expand /main/DUT/X_TRU/req_i
add wave -noupdate -expand /main/DUT/X_TRU/resp_o
add wave -noupdate /main/DUT/X_TRU/rst_n_i
add wave -noupdate -expand /main/DUT/X_TRU/rtu_i
add wave -noupdate /main/DUT/X_TRU/s_bank_swap_on_trans
add wave -noupdate /main/DUT/X_TRU/s_config
add wave -noupdate /main/DUT/X_TRU/s_endpoint_array
add wave -noupdate /main/DUT/X_TRU/s_endpoints
add wave -noupdate /main/DUT/X_TRU/s_regs_fromwb
add wave -noupdate -expand /main/DUT/X_TRU/s_regs_towb
add wave -noupdate /main/DUT/X_TRU/s_trans_ep_ctr
add wave -noupdate /main/DUT/X_TRU/s_trans_rxFrameMask
add wave -noupdate /main/DUT/X_TRU/s_transitionActive
add wave -noupdate /main/DUT/X_TRU/s_transitionFinished
add wave -noupdate /main/DUT/X_TRU/s_tru_rd_addr
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_addr
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_bank
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_entry
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_rd_subentry_arr
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_wr_index
add wave -noupdate /main/DUT/X_TRU/s_tru_tab_wr_subentry_arr
add wave -noupdate /main/DUT/X_TRU/s_tru_wr_addr
add wave -noupdate /main/DUT/X_TRU/s_tru_wr_data
add wave -noupdate /main/DUT/X_TRU/s_tru_wr_ena
add wave -noupdate /main/DUT/X_TRU/s_tx_rt_reconf_FRM
add wave -noupdate /main/DUT/X_TRU/swc_o
add wave -noupdate /main/DUT/X_TRU/wb_ack_o
add wave -noupdate /main/DUT/X_TRU/wb_addr_i
add wave -noupdate /main/DUT/X_TRU/wb_cyc_i
add wave -noupdate /main/DUT/X_TRU/wb_data_i
add wave -noupdate /main/DUT/X_TRU/wb_data_o
add wave -noupdate /main/DUT/X_TRU/wb_sel_i
add wave -noupdate /main/DUT/X_TRU/wb_stb_i
add wave -noupdate /main/DUT/X_TRU/wb_we_i
add wave -noupdate -divider Port
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/clk_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/config_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/endpoints_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/g_num_ports
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/g_pattern_width
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/g_patternID_width
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/g_tru_addr_width
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/g_tru_subentry_num
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/rst_n_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_drop
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_egress_mask
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_ingress_mask
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_patternAdd
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_patternAdd_d0
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_patternRep
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_patternRep_d0
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_port_mask
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_portID_vec
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_reqMask_d0
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_reqMask_d1
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_resp_masks
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_self_mask
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_status_mask
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_valid_d0
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_valid_d1
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/s_zeros
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/tru_req_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/tru_resp_o
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/tru_tab_addr_o
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/tru_tab_entry_i
add wave -noupdate /main/DUT/X_TRU/U_T_PORT/txFrameMask_o
add wave -noupdate -divider Endpoint_0
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/clk_i
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/endpoint_o
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/g_num_ports
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/g_pattern_width
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/g_patternID_width
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/g_stableUP_treshold
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/g_tru_subentry_num
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/port_if_ctrl_o
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/port_if_i
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/reset_rxFlag_i
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/rst_n_i
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/rtu_pass_all_i
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_port_down
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_port_status_d0
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_rxFrameMask
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_rxFrameMaskReg
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_stableUp_cnt
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_tru_port_state
add wave -noupdate /main/DUT/X_TRU/G_ENDP(0)/U_T_ENDPOINT/s_zeros
add wave -noupdate -divider Transition
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/clk_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/config_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/endpoints_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/ep_o
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/g_mt_trans_max_fr_cnt
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/g_num_ports
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/g_prio_width
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/rst_n_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/rtu_i
add wave -noupdate -expand /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/rxFrameMask_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_ep_ctr_A
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_ep_ctr_B
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_ep_zero
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_A_mask
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_A_prio
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_A_rtu_srobe
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_B_mask
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_B_prio
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_port_B_rtu_srobe
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_portA_frame_cnt
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_portB_frame_cnt
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_start_transition
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_statTransActive
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_statTransFinished
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/s_tru_trans_state
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/statTransActive_o
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/statTransFinished_o
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/tru_tab_bank_i
add wave -noupdate /main/DUT/X_TRU/U_TRANSITION/TRANS_MARKER_TRIG/tru_tab_bank_o
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {12304389440 fs} 0}
configure wave -namecolwidth 224
configure wave -valuecolwidth 81
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {12057224390 fs} {13143231700 fs}
