files = [
  "tru_wbgen2_pkg.vhd",  
  "wrsw_tru_pkg.vhd",
  "xwrsw_tru.vhd",
#  "wrsw_tru.vhd",
  "wrsw_tru_wb.vhd",
  "tru_port.vhd",
  "tru_reconfig_rt_port_handler.vhd",
  "tru_sub_vlan_pattern.vhd",
  "tru_wishbone_slave.vhd",
#  "tru_port_wrapper.vhd",
  "tru_endpoint.vhd",
  "tru_transition.vhd",
  "tru_trans_marker_trig.vhd",
  "tru_trans_lacp_dist.vhd",
  "tru_trans_lacp_colect.vhd",
  "../wrsw_shared_types_pkg.vhd",
  "../wrsw_rtu/rtu_private_pkg.vhd",
  "../wrsw_rtu/rtu_wbgen2_pkg.vhd",
  "../../ip_cores/general-cores/modules/wishbone/wishbone_pkg.vhd",
  #"../../ip_cores/general-cores/modules/genrams/genram_pkg.vhd",
  "../../ip_cores/general-cores/modules/common/gencores_pkg.vhd",
  "../../ip_cores/general-cores/modules/wishbone/wbgen2/wbgen2_pkg.vhd"
  ]