onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/cyc_prev
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/trans_index
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/first_transaction
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/settings
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/cyc_start
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/cyc_end
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/clk_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/rst_n_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/src_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/src_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/addr_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/data_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/dvalid_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/sof_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/eof_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/error_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/bytesel_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/dreq_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/q_valid
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/full
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/we
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/rd
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/fin
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/fout
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/pre_dvalid
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/pre_eof
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/pre_data
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/pre_addr
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/post_dvalid
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/post_eof
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/post_sof
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/gen_port_connections(0)/conv_wrf_to_wb/err_status
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/src_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/u_xswc_core/src_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_dat_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_adr_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_sel_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_cyc_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_stb_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_we_0_o
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_stall_0_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_ack_0_i
add wave -noupdate /main/DUT_xswcore_wrapper/DUT_xswc_core_7_ports_wrapper/src_err_0_i
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/g_addr_width
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/g_data_width
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/clk_i
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/rst_n_i
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/adr
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/dat_i
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/sel
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/dat_o
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/ack
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/stall
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/err
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/rty
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/cyc
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/stb
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/we
add wave -noupdate /main/DUT_xswcore_wrapper/snk_0/last_access_t
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4406260 ps} 0}
configure wave -namecolwidth 421
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {31516355 ps}
