onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /main/DUT/ALLOC_CORE/g_num_pages
add wave -noupdate /main/DUT/ALLOC_CORE/g_page_addr_width
add wave -noupdate /main/DUT/ALLOC_CORE/g_num_ports
add wave -noupdate /main/DUT/ALLOC_CORE/g_usecount_width
add wave -noupdate /main/DUT/ALLOC_CORE/clk_i
add wave -noupdate /main/DUT/ALLOC_CORE/rst_n_i
add wave -noupdate /main/DUT/ALLOC_CORE/alloc_i
add wave -noupdate /main/DUT/ALLOC_CORE/free_i
add wave -noupdate /main/DUT/ALLOC_CORE/force_free_i
add wave -noupdate /main/DUT/ALLOC_CORE/set_usecnt_i
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_i
add wave -noupdate /main/DUT/ALLOC_CORE/pgaddr_i
add wave -noupdate /main/DUT/ALLOC_CORE/pgaddr_o
add wave -noupdate /main/DUT/ALLOC_CORE/free_last_usecnt_o
add wave -noupdate /main/DUT/ALLOC_CORE/done_o
add wave -noupdate /main/DUT/ALLOC_CORE/nomem_o
add wave -noupdate /main/DUT/ALLOC_CORE/nomem
add wave -noupdate /main/DUT/ALLOC_CORE/rd_ptr
add wave -noupdate /main/DUT/ALLOC_CORE/wr_ptr
add wave -noupdate /main/DUT/ALLOC_CORE/free_pages
add wave -noupdate /main/DUT/ALLOC_CORE/q_write
add wave -noupdate /main/DUT/ALLOC_CORE/q_read
add wave -noupdate /main/DUT/ALLOC_CORE/pending_free
add wave -noupdate /main/DUT/ALLOC_CORE/read_usecnt
add wave -noupdate /main/DUT/ALLOC_CORE/q_init_data
add wave -noupdate /main/DUT/ALLOC_CORE/initializing
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_write
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_addr
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_rddata
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_wrdata
add wave -noupdate /main/DUT/ALLOC_CORE/q_output_addr
add wave -noupdate /main/DUT/ALLOC_CORE/alloc_d0
add wave -noupdate /main/DUT/ALLOC_CORE/force_free_d0
add wave -noupdate /main/DUT/ALLOC_CORE/free_d0
add wave -noupdate /main/DUT/ALLOC_CORE/done_int
add wave -noupdate /main/DUT/ALLOC_CORE/ram_ones
add wave -noupdate /main/DUT/ALLOC_CORE/tmp_dbg_dealloc
add wave -noupdate /main/DUT/ALLOC_CORE/tmp_page
add wave -noupdate /main/DUT/ALLOC_CORE/free_blocks
add wave -noupdate /main/DUT/ALLOC_CORE/usecnt_not_zero
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1845342710 fs} 0}
configure wave -namecolwidth 192
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits fs
update
WaveRestoreZoom {0 fs} {21 us}
