---------------------------------------------------------------------------------------
-- Title          : Wishbone slave core for WR Switch aux clock generation module
---------------------------------------------------------------------------------------
-- File           : gen10_wbgen2_pkg.vhd
-- Author         : auto-generated by wbgen2 from wrsw_gen_10mhz.wb
-- Created        : Wed Dec  3 13:36:18 2014
-- Standard       : VHDL'87
---------------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE wrsw_gen_10mhz.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
---------------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

package gen10_wbgen2_pkg is
  
  
  -- Input registers (user design -> WB slave)
  
  type t_gen10_in_registers is record
    psr_cur_val_i                            : std_logic_vector(4 downto 0);
    psr_lck_i                                : std_logic;
    end record;
  
  constant c_gen10_in_registers_init_value: t_gen10_in_registers := (
    psr_cur_val_i => (others => '0'),
    psr_lck_i => '0'
    );
    
    -- Output registers (WB slave -> user design)
    
    type t_gen10_out_registers is record
      pr_hp_width_o                            : std_logic_vector(15 downto 0);
      pr_hp_width_wr_o                         : std_logic;
      dcr_low_width_o                          : std_logic_vector(15 downto 0);
      dcr_low_width_wr_o                       : std_logic;
      csr_o                                    : std_logic_vector(15 downto 0);
      csr_wr_o                                 : std_logic;
      psr_set_val_o                            : std_logic_vector(4 downto 0);
      psr_set_val_wr_o                         : std_logic;
      end record;
    
    constant c_gen10_out_registers_init_value: t_gen10_out_registers := (
      pr_hp_width_o => (others => '0'),
      pr_hp_width_wr_o => '0',
      dcr_low_width_o => (others => '0'),
      dcr_low_width_wr_o => '0',
      csr_o => (others => '0'),
      csr_wr_o => '0',
      psr_set_val_o => (others => '0'),
      psr_set_val_wr_o => '0'
      );
    function "or" (left, right: t_gen10_in_registers) return t_gen10_in_registers;
    function f_x_to_zero (x:std_logic) return std_logic;
    function f_x_to_zero (x:std_logic_vector) return std_logic_vector;
end package;

package body gen10_wbgen2_pkg is
function f_x_to_zero (x:std_logic) return std_logic is
begin
if(x = 'X' or x = 'U') then
return '0';
else
return x;
end if; 
end function;
function f_x_to_zero (x:std_logic_vector) return std_logic_vector is
variable tmp: std_logic_vector(x'length-1 downto 0);
begin
for i in 0 to x'length-1 loop
if(x(i) = 'X' or x(i) = 'U') then
tmp(i):= '0';
else
tmp(i):=x(i);
end if; 
end loop; 
return tmp;
end function;
function "or" (left, right: t_gen10_in_registers) return t_gen10_in_registers is
variable tmp: t_gen10_in_registers;
begin
tmp.psr_cur_val_i := f_x_to_zero(left.psr_cur_val_i) or f_x_to_zero(right.psr_cur_val_i);
tmp.psr_lck_i := f_x_to_zero(left.psr_lck_i) or f_x_to_zero(right.psr_lck_i);
return tmp;
end function;
end package body;
